get_data_names <- function() {
    c("did", "tra_id", "pat_id", "Sjukhuskod", "PersonIdentity", 
      "TempIdentity", "DOB", "Deceased", "DeceasedDate", "pt_age_yrs", 
      "Gender", "pt_Gender", "inj_dominant", "inj_mechanism", "inj_intention", 
      "pt_asa_preinjury", "pre_card_arrest", "pre_gcs_sum", "pre_gcs_motor", 
      "ed_gcs_sum", "ed_gcs_motor", "pre_sbp_value", "pre_sbp_rtscat", 
      "ed_sbp_value", "ed_sbp_rtscat", "pre_rr_value", "pre_rr_rtscat", 
      "ed_rr_value", "ed_rr_rtscat", "ed_be_art", "ed_be_art_NotDone", 
      "ed_inr", "ed_inr_NotDone", "hosp_vent_days", "host_vent_days_NotDone", 
      "hosp_los_days", "hosp_dischg_dest", "res_gos_dischg", "res_survival", 
      "TraumaAlarmCriteria", "TraumaAlarmAtHospital", "AlarmRePrioritised", 
      "ISS", "NISS", "DateTime_Of_Trauma", "DateTime_of_Alarm", "DateTime_ArrivalAtScene", 
      "DateTime_LeaveScene", "DateTime_ArrivalAtHospital", "DateTime_FirstNormalBasecess", 
      "DateTime_FirstTraumaDT", "FirstTraumaDT_NotDone", "DateTime_StartofTreatment", 
      "dt_alarm_hosp", "pre_provided", "pre_intubated", "pre_intub_type", 
      "ed_intubated", "ed_intub_type", "pre_transport", "ed_emerg_proc", 
      "ed_emerg_proc_other", "ed_tta", "host_transfered", "host_care_level", 
      "dt_alarm_scene", "dt_ed_norm_be", "dt_ed_first_ct", "dt_ed_emerg_proc", 
      "Date_Discharged", "tra_DodsfallsanalysGenomford", "Fr1.1", "Fr1.2", 
      "Fr1.3", "Fr1.4", "Fr1.5", "Fr1.6", "Fr1.8", "Fr1.9", "Fr1.10", 
      "Fr1.11", "Fr1.12", "Fr1.13", "Fr1.14", "Fr1.15", "NumberOfActions", 
      "pac_code_01", "pac_code_02", "pac_code_03", "pac_code_04", "pac_code_05", 
      "pac_code_06", "pac_code_07", "pac_code_08", "pac_code_09", "pac_code_10", 
      "pac_code_11", "pac_code_12", "pac_code_13", "pac_code_14", "pac_code_15", 
      "NumberOfInjuries", "ICD_01", "ICD_02", "ICD_03", "ICD_04", "ICD_05", 
      "ICD_06", "ICD_07", "ICD_08", "ICD_09", "ICD_10", "ICD_11", "ICD_12", 
      "ICD_13", "ICD_14", "ICD_15", "ICD_16", "ICD_17", "ICD_18", "ICD_19", 
      "ICD_20", "ICD_21", "ICD_22", "ICD_23", "ICD_24", "ICD_25", "ICD_26", 
      "ICD_27", "ICD_28", "ICD_29", "ICD_30", "ICD_31", "ICD_32", "ICD_33", 
      "ICD_34", "ICD_35", "ICD_36", "ICD_37", "ICD_38", "ICD_39", "ICD_40", 
      "ICD_41", "ICD_42", "ICD_43", "ICD_44", "ICD_45", "ICD_46", "ICD_47", 
      "ICD_48", "ICD_49", "ICD_50", "AISCode_01", "AISCode_02", "AISCode_03", 
      "AISCode_04", "AISCode_05", "AISCode_06", "AISCode_07", "AISCode_08", 
      "AISCode_09", "AISCode_10", "AISCode_11", "AISCode_12", "AISCode_13", 
      "AISCode_14", "AISCode_15", "AISCode_16", "AISCode_17", "AISCode_18", 
      "AISCode_19", "AISCode_20", "AISCode_21", "AISCode_22", "AISCode_23", 
      "AISCode_24", "AISCode_25", "AISCode_26", "AISCode_27", "AISCode_28", 
      "AISCode_29", "AISCode_30", "AISCode_31", "AISCode_32", "AISCode_33", 
      "AISCode_34", "AISCode_35", "AISCode_36", "AISCode_37", "AISCode_38", 
      "AISCode_39", "AISCode_40", "AISCode_41", "AISCode_42", "AISCode_43", 
      "AISCode_44", "AISCode_45", "AISCode_46", "AISCode_47", "AISCode_48", 
      "AISCode_49", "AISCode_50", "id", "arrival", "ISS_moore_15_trauma_3", 
      "bedomn_primar_granskning", "pat_personnummer", "ISS_less_15_trauma_1_2", 
      "pat_TempPersonnummer", "Fr16", "korrekt_triage", "tid_skadeplats_moore_20min", 
      "tid_skadeplats", "GCS_less13_DT_moore_120", "Riktlinje", "Fr1_6", 
      "origin", "Ankomst_te", "Personnummer", "Reservnummer", "Kön", 
      "Tr_Nivå", "tillavdelning_Direkt_eft_TE_AKM", "IVA_efter_TE", 
      "IVA_eft_avd", "iva_dagar_n", "iva_vardtillfallen_n", "Död.datum", 
      "uppfolj_30_dgr", "Klar", "SweTr", "Flyttad_till_avd_eft_iva", 
      "inlagd_swetrau", "waran_beh_vid_ank", "noak_vid_ankomst", "VK_hlr_thorak", 
      "VK_sap_less90", "VK_leverskada", "VK_gcs_less9_ej_intubTE", 
      "VK_mjaltskada", "VK_mer_30min_DT", "VK_mass_transf", "VK_mer_60min_interv", 
      "VK_iss_15_ej_iva", "VK_ej_trombrof_TBI_72h", "VK_iss_15_ej_TE", 
      "VK_annat", "VK_avslutad", "Problemomrade_.FMP")
}
